# Generated by Django 5.2.2 on 2025-06-12 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='stamina',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='study',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='wealth',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '대분류'), (2, '중분류'), (3, '소분류')], default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rpg.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategoryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
